apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: ballot
  name: {{ .Values.services.ballot.serviceName }}
  namespace: {{ .Values.namespace }}
spec: 
  selector: 
    app: ballot
  ports:
  - name: http
    port: {{ .Values.httpServicePort }}
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballot
  namespace: {{ .Values.namespace }}
  labels:
    roost.ai/fitness.git-type: github
    roost.ai/fitness.git-repo-name: voting_app
    roost.ai/fitness.git-org: roost-io
    roost.ai/fitness.git-branch: roost-eaas
    roost.ai/fitness.git-test-path: ballot.test
    roost.ai/fitness.test-type: artillery
    # roost.ai/fitness.artillery-env: "prod"  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ballot
  template:
    metadata:
      labels:
        app: ballot
    spec:
      containers:
      - name: ballot
        image: '{{- printf "%s/%s:%s" .Values.registry .Values.services.ballot.imageName .Values.tag -}}'
        ports:
        - containerPort: 8080
